[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader',
    'php artisan storage:link',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache'
]

[phases.build]
cmds = ['npm ci && npm run build']

[variables]
UPLOAD_MAX_FILESIZE = '1024M'
POST_MAX_SIZE = '1024M'
MAX_EXECUTION_TIME = '900'
MAX_INPUT_TIME = '900'
MEMORY_LIMIT = '1024M'

[start]
cmd = 'php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT'